name: Feature request
description: Suggest an idea for Nabby
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How should it work?
  - type: textarea
    id: tabby
    attributes:
      label: Does Tabby desktop have this? How does it work there?
